apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-iimt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-iimt
    app.kubernetes.io/part-of: tkrw-pr712-0075-0045-app
  name: devfile-sample-iimt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-iimt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-iimt
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-iimt@sha256:7aeda360a298f4a26c8874ab382b5d4e4b9148a48cb42bd5fea713c0fd19a1ff
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
