apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-iimt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-iimt@sha256:7aeda360a298f4a26c8874ab382b5d4e4b9148a48cb42bd5fea713c0fd19a1ff
        name: my-nodejs
        resources: {}
status: {}
